// MASSIF token build — zero external dependencies (node stdlib only).
// Mirrors the house build FORMAT (DTCG walk -> CSS custom properties) but emits
// the MASSIF identity under the --mf- prefix. NO visual identity is inherited
// from any other source; only this build shape is shared.
// Usage: node build-tokens.mjs   ->   writes tokens.css next to this file.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const inFile = join(here, 'tokens.json');
const outFile = join(here, 'tokens.css');

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const lines = [];
const walk = (node, path) => {
  if (node && typeof node === 'object' && '$value' in node) {
    const name = ['mf', ...path.map(kebab)].join('-');
    const raw = node.$value;
    const value = Array.isArray(raw)
      ? raw.map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ')
      : String(raw);
    lines.push(`  --${name}: ${value};`);
    return;
  }
  if (node && typeof node === 'object') {
    for (const key of Object.keys(node)) {
      if (key.startsWith('$')) continue;
      walk(node[key], [...path, key]);
    }
  }
};

const tokens = JSON.parse(readFileSync(inFile, 'utf8'));
walk(tokens, []);

const css = `/* GENERATED by build-tokens.mjs from tokens.json — do not edit by hand.
 * MASSIF (gen-004) identity tokens, prefix --mf-. Palette anchored verbatim to
 * the m1nd design system; extension is by luminance only. */
:root {
${lines.join('\n')}
}
`;
writeFileSync(outFile, css);
console.log(`Generated ${outFile} — ${lines.length} custom properties.`);
